In [1]:
import numpy as np

In [3]:
my_list = list(range(100000))

In [4]:
n_array = np.arange(100000)

In [5]:
%time np.sum(n_array ** 2)

CPU times: total: 0 ns
Wall time: 2 ms


216474736

In [6]:
%time sum([x ** 2 for x in my_list])

CPU times: total: 15.6 ms
Wall time: 13.3 ms


333328333350000

In [7]:
# array_ismi[index_numarası]

In [8]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[0], arr[1])

1 2


In [9]:
# array_ismi[[array_num, array_num2, array_num3]]

print(arr[[0,3,5]])

[1 4 6]


In [11]:
arr[[-1,-2,-4]]

array([7, 6, 4])

In [13]:
arr[1:6:2]

array([2, 4, 6])

In [15]:
arr[-1::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [16]:
# 0-D Arrayler -Elemanlarına scalar denilir

arr = np.array(41)

print(arr)

41


In [17]:
# 1-D Arraylerin elemanları 0-D arraylerden oluşur.
# Yani scalar lardan olusur


In [18]:
# 2-D Arrayler
# 2-D Arrayler 1-D arrayleri eleman olarak alan arraylerdir.

arr = np.array([[1,2,3]])

print(arr)


[[1 2 3]]


In [19]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
print('1.satırın 2.elemanı : ', arr[0, 1])

1.satırın 2.elemanı :  2


In [23]:
# 2.satırın 5.elemanı

print('2.satırın 5.elemanı ', arr[1, 4])

2.satırın 5.elemanı  10


In [24]:
print('1.satırın 2.elemanı : ', arr[0][1])

1.satırın 2.elemanı :  2


In [25]:
# 3-D Arrayler 2-D arrayleri eleman olarak alırlar

In [26]:
arr = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [27]:
print(arr[0, 1, 2 ])

6


In [28]:
arr = np.array(23)

arr.shape

()

In [29]:
arr = np.array([0, 1, 2 ])

arr.shape

(3,)

In [35]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [31]:
arr = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])

arr.shape

(2, 2, 3)

In [32]:
arr.ndim


3

In [38]:
# append() zrounlu parametreleri ; array_ismi values
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [[4, 5, 6], [7, 8, 9]])
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
new_arr = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]])

print(new_arr)

[1 2 3 4 5 6 7 8 9]


In [40]:
# arr = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

arr= np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
new_arr = np.append(arr, [[7, 8, 9]], axis=0)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
new_arr = np.append(arr, [[7, 8, 9]], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [44]:
b = np.array([[1,2,3],[4,5,6]]) 

In [45]:
print(b)

[[1 2 3]
 [4 5 6]]


In [49]:
new_b = np.append(b, [[5,5,5,5],[7,8,9,10]], axis = 1)

print(new_b)

[[ 1  2  3  5  5  5  5]
 [ 4  5  6  7  8  9 10]]


In [50]:
# insert()  zorunlu parametreleri ; array, obj , eklenecek_değerler
# axis opsiyonel default olarak flattened array oluşturur
# obj ekleme yapacağınız indexleri belirtiebilirsiniz


In [51]:
arr = np.array([2, 3, 4, 5, 6, 7])

new_arr = np.insert(arr, 2, 9)

In [52]:
print(new_arr)

[2 3 9 4 5 6 7]


In [53]:
a = np.array([[1, 1], [2, 2], [3, 3]])

print(a)

[[1 1]
 [2 2]
 [3 3]]


In [54]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [55]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [56]:
np.insert(a, 0, 5, axis=1)

array([[5, 1, 1],
       [5, 2, 2],
       [5, 3, 3]])

In [57]:
np.insert(a, 1, 5, axis=0)

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

In [58]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [1, 1],
       [2, 2],
       [3, 3]])

In [59]:
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [66]:
np.insert(a, 3, 5.2, axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [5, 5]])

In [67]:
a = np.array([[1, 1], [2, 2], [3, 3]])

In [68]:
print (a)

[[1 1]
 [2 2]
 [3 3]]


In [69]:
np.insert(a, [1], [[4],[5],[6]], axis=1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [70]:
np.insert(a, [1], [4,5,6], axis=1)

array([[1, 4, 5, 6, 1],
       [2, 4, 5, 6, 2],
       [3, 4, 5, 6, 3]])

In [71]:
np.insert(a, 1, [[4],[5],[6]], axis=1)

array([[1, 4, 5, 6, 1],
       [2, 4, 5, 6, 2],
       [3, 4, 5, 6, 3]])

In [72]:
np.array_equal(np.insert(a, 1, [1, 2, 3], axis=1),
               np.insert(a, [1], [[1],[2],[3]], axis=1))

True

In [73]:
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [74]:
np.insert(a, 1, [4,5,6], axis=1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [75]:
np.insert(a, [1], [[4],[5],[6]], axis=1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [77]:
b = np.array([1, 1, 2, 2, 3, 3])
new_b = np.insert(b, slice(2,4), [5,6])
print(new_b)

[1 1 5 2 6 2 3 3]


In [78]:
b

array([1, 1, 2, 2, 3, 3])

In [79]:
np.insert(b, [2, 2], [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [80]:
np.insert(b, 2, [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [84]:
b


array([1, 1, 2, 2, 3, 3])

In [85]:
np.insert(b, 2, [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [86]:
np.insert(b, [2, 3], [5, 6])

array([1, 1, 5, 2, 6, 2, 3, 3])

In [87]:
a = np.array([[1, 1], [2, 2], [3, 3]])

print(a)

[[1 1]
 [2 2]
 [3 3]]


In [88]:
np.insert(a, 1, [5, 6]) 

array([1, 5, 6, 1, 2, 2, 3, 3])

In [89]:
np.insert(a, [1], [5, 6])

array([1, 5, 6, 1, 2, 2, 3, 3])

In [90]:
np.array_equal(np.insert(a, 1, [5, 6]),
               np.insert(a, [1], [5, 6]) )

True

In [92]:
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [93]:
np.insert(a, [1], [[5], [6]], axis=0)

array([[1, 1],
       [5, 5],
       [6, 6],
       [2, 2],
       [3, 3]])

In [94]:
np.insert(a, [1], [5, 6], axis=0)

array([[1, 1],
       [5, 6],
       [2, 2],
       [3, 3]])

In [102]:
np.insert(a, 1, [5, 6], axis=0)

array([[1, 1],
       [5, 6],
       [2, 2],
       [3, 3]])

In [98]:
np.insert(a, 1, [[5], [6]], axis=1)

array([[1, 5, 6, 1],
       [2, 5, 6, 2],
       [3, 5, 6, 3]])

In [99]:
np.insert(a, [1], [[5], [6]], axis=1)

ValueError: could not broadcast input array from shape (2,1) into shape (3,1)

In [100]:
a=np.array([[1,1],[2,2],[3,3]])

print(a)

np.insert(a,1,[4,5,6],axis=1)


[[1 1]
 [2 2]
 [3 3]]


array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [101]:
np.insert(a,[1],[4,5,6],axis=1)

array([[1, 4, 5, 6, 1],
       [2, 4, 5, 6, 2],
       [3, 4, 5, 6, 3]])