Arraylerde Arama Yapma | where() 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,4,4])

In [3]:
x = np.where((arr == 4))
print(x)

(array([3, 5, 6], dtype=int64),)


In [4]:
x2 = np.where((arr <= 2) & (arr % 2 == 0))
print(x2)

(array([1], dtype=int64),)


In [5]:
x3 = np.where((arr <= 2) | (arr % 2 == 0))
print(x3)

(array([0, 1, 3, 5, 6], dtype=int64),)


In [6]:
# Numpy'da rastgele sayi uretme methodlari

In [7]:
from numpy import random

In [9]:
y = random.randint(100)
print(y) 

99


In [11]:
y1 = random.randint(5,15)
print(y1)

9


In [12]:
y2 = random.randint(2)
print(y2)

1


In [13]:
arr2 = np.random.randint(2,size = 10)  # shape(10,) gibi demek
print(arr2)

[1 1 0 0 1 1 1 0 0 1]


In [14]:
arr3 = np.random.randint(8,size = 10)  
print(arr3)

[2 5 2 6 2 2 6 7 4 2]


In [15]:
# shape(3,4)

arr4 = np.random.randint(8,size = (3,4))
print(arr4)

[[7 5 6 2]
 [0 5 3 7]
 [2 2 2 0]]


In [18]:
arr4 = np.random.randint(8,size = (4,3,2))
print(arr4)

[[[7 4]
  [4 3]
  [3 0]]

 [[4 0]
  [3 1]
  [5 3]]

 [[0 3]
  [7 3]
  [2 1]]

 [[0 2]
  [1 4]
  [1 2]]]


In [19]:
# rand() float sayilar uretir

In [21]:
z = random.rand()
print(z)

0.5755196780846833


In [23]:
z1 = np.random.rand(3,2)   # shape(3,2)   size'a gerek yok direkt size olarak alir
print(z1)

[[0.06278271 0.97033521]
 [0.32982738 0.61630608]
 [0.88518315 0.30415126]]


In [24]:
z2 = np.random.rand(3,2,2)
print(z2)

[[[0.03199997 0.65997972]
  [0.04610441 0.71186741]]

 [[0.70248521 0.11727756]
  [0.08405319 0.64966682]]

 [[0.37852436 0.69240257]
  [0.19084089 0.43225049]]]


In [25]:
# zeros() methodu 0'lar ureten bir metoddur 

In [27]:
k1 = np.zeros(3)
print(k1)

[0. 0. 0.]


In [28]:
k2 = np.zeros(5,dtype = 'int')
k2

array([0, 0, 0, 0, 0])

In [29]:
k3 = np.zeros((1,2),dtype = 'int')
k3

array([[0, 0]])

In [30]:
k4 = np.zeros((2,4,1),dtype = 'int')
k4

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

In [31]:
k5 = np.zeros((2,4,1),dtype = bool)
k5

array([[[False],
        [False],
        [False],
        [False]],

       [[False],
        [False],
        [False],
        [False]]])

In [ ]:
# zeros_like() bu methoda parametre olarak array veriliyor 
#o arrayle ayni data tipine ait olan arrayi geri donderir

In [32]:
m = np.arange(48).reshape(3,4,4)
print(m)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [33]:
zlike_arr = np.zeros_like(m)
print(zlike_arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [34]:
# ones() methodu deger olarak birler ureten method

In [35]:
arr_ones = np.ones(5)
print(arr_ones)

[1. 1. 1. 1. 1.]


In [36]:
arr_ones2 = np.ones(5,dtype = 'int')
arr_ones2

array([1, 1, 1, 1, 1])

In [39]:
arr_ones3 = np.ones((2,5,3),dtype = 'int')
arr_ones3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [40]:
# ones_like() 

In [41]:
n = np.arange(48).reshape(3,4,4)
print(n)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [42]:
n2 = np.ones_like(n)
print(n2)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [43]:
# eye()  parametre olarak ciktida istenilen satir sayisini alir

np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [44]:
np.eye(2, dtype = 'int')

array([[1, 0],
       [0, 1]])

In [45]:
np.eye(3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
# transpose()

t = np.arange(4).reshape((2,2))
print(t)

[[0 1]
 [2 3]]


In [48]:
np.transpose(t)

array([[0, 2],
       [1, 3]])

In [49]:
t1 = np.ones((1,2,3),dtype = 'int')
t1

array([[[1, 1, 1],
        [1, 1, 1]]])

In [54]:
np.transpose(t1)   #shape'i ters cevirir

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

In [52]:
t1.shape

(1, 2, 3)

In [53]:
np.transpose(t1).shape

(3, 2, 1)

In [55]:
t2 = np.ones((2,3,4,5),dtype=int)
t2

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

In [56]:
np.transpose(t2).shape

(5, 4, 3, 2)

In [57]:
# empty()
# parametre olarak shape alir verilen shape'i bir arrayin girdiler degerler olmadan kendisi belirler

In [60]:
t3 = np.empty((5),dtype = int)
print(t3)

[-1544654192         520           0           0      131074]


In [63]:
t4 = np.empty((2,5),dtype = int)
print(t4)

[[         0 1072693248          0 1072693248          0]
 [1072693248          0 1072693248          0 1072693248]]


In [64]:
t5 = np.array([[1,2,3],[4,5,6]])
t5

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.empty_like(t5)

array([[-1566203216,         520,           0],
       [          0,           1,  1912602624]])

In [66]:
# full() 
b1 = np.full(5,10)
b1

array([10, 10, 10, 10, 10])

In [67]:
b2 = np.full(5,[1,2,3,4,5])
b2

array([1, 2, 3, 4, 5])

In [70]:
b3 = np.full((2,6),[1,2,3,4,5,6])   # her bir eleman icin bu arrayi yazar direkt
b3

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [72]:
b4 = np.full((1,2),9)
b4

array([[9, 9]])

In [73]:
b4 = np.full((2,2),9)
b4

array([[9, 9],
       [9, 9]])

In [74]:
b4 = np.full((4,2),7)
b4

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [75]:
# full_like() girilen degerin degerine ve shape'ine gore full array olusturur

In [77]:
d1 = np.arange(6,dtype = int)
d1

array([0, 1, 2, 3, 4, 5])

In [79]:
d2 = np.full_like(d1,3)
d2

array([3, 3, 3, 3, 3, 3])

In [80]:
# rollaxis()
    
# array,axis


In [81]:
a = np.arange(8)

b = np.reshape(a,(2,4))

b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
b.shape

(2, 4)

In [83]:
np.rollaxis(b,1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [84]:
np.rollaxis(b,1).shape

(4, 2)

In [85]:
q = np.ones((3,4,5,6))
q.shape

(3, 4, 5, 6)

In [88]:
np.rollaxis(q,3,1).shape

(3, 6, 4, 5)

In [89]:
np.rollaxis(q,3).shape

(6, 3, 4, 5)